
name: CI-CD-Pipeline-to-AWS-ElasticBeanstalk
env:
  EB_PACKAGE_S3_BUCKET_NAME: "vladelleus-html-packages"
  EB_APPLICATION_NAME: "Myhtml"
  EB_ENVIRONMENT_NAME: "Myhtml-env"
  DEPLOY_PACKAGE_NAME: "python_app_${{ github.sha }}.zip"
  AWS_REGION_NAME: "eu-west-2"

on: 
  push:
    branches:
      - master
jobs:
  my_ci_part: 
    runs-on: ubuntu-latest
    
    steps:
      -name: Git clone the repo
      uses: actions/checkout/@v1
    
      -name: Create zip deploy package
       run : zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
       
       
       
       
       
       
